/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.client;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;

import org.example.utilities.StandardInputUtil;

public class Client {
    public static void main(String[] args) {
        if (args.length != 2) {
            System.err.println(
                "Usage: java Client <host name> <port number>");
            System.exit(1);
        }
 
        String hostName = args[0];
        int portNumber = Integer.parseInt(args[1]);
 
        try {
            Socket echoSocket = new Socket(hostName, portNumber);
            PrintWriter out =
                new PrintWriter(echoSocket.getOutputStream(), true);
            BufferedReader in =
                new BufferedReader(
                    new InputStreamReader(echoSocket.getInputStream()));
            
            String serverResponse = in.readLine();
            System.out.println("Server: " + serverResponse);
            
            if (serverResponse.equals("Server is busy. Try again later.")) {
                echoSocket.close();
                return;
            }

            String userInput;
            while (!(userInput = StandardInputUtil.readLine()).equals("quit")) {
                out.println(userInput);
                System.out.println("Echo Server Sent: " + in.readLine());
            }
            out.println(userInput); //send "quit" to server
            echoSocket.close();

        } catch (UnknownHostException e) {
            System.err.println("Don't know about host " + hostName);
            System.exit(1);
        } catch (IOException e) {
            System.err.println("Couldn't get I/O for the connection to " +
                hostName);
            System.exit(1);
        } 
    }
}
